### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by caot**
added export BOOST_ROOT=/PATH_TO/boost-1.56.0

### CODE REVIEW

**Comment by ctsa** [comment]
Thank you for reporting this, could you describe the problem you encountered? I don't see any issue building manta with boost 1.63 or 1.64 so we'd need more information about your case to make a fix.

**Comment by caot** [comment]
Here you can see some Boost component NOT FOUND for "-- Boost version: 1.63.0".

$ ../configure --prefix=$HOME/manta-1.1.1
......cmake......
cmake version 2.8.12 (>= 2.8.4) is already installed
Using existing cmake: cmake
-- ==== Initializing project cmake configuration ====
-- BUILD_TYPE: Release
-- CMAKE_PARALLEL: 1
-- TARGET_ARCHITECTURE: x86_64
-- install prefix: /home/tangc/manta-1.1.1
-- Boost version: 1.63.0
-- Boost component: date_time	status: NOT FOUND
-- Boost component: filesystem	status: NOT FOUND
-- Boost component: program_options	status: NOT FOUND
-- Boost component: regex	status: NOT FOUND
-- Boost component: serialization	status: NOT FOUND
-- Boost component: system	status: NOT FOUND
-- Boost component: timer	status: NOT FOUND
-- Boost component: chrono	status: NOT FOUND
-- Boost component: unit_test_framework	status: NOT FOUND
-- Boost version 1.56.0 or higher not found. Boost will be built from the distribution...
-- Unpacking boost library source

**Comment by ctsa** [comment]
This might reflect too much divergence between cmake and boost versions. As a general rule you do not want your cmake version to be older than the libraries you are asking cmake to detect. This is not a manta constraint but just the way cmake works when used to configure any package.

**Comment by ctsa** [comment]
Found a probable explanation: manta requires static boost libraries -- the behavior you're seeing is consistent with a boost library which was build with dynamic libraries only. I will edit the installation docs to clarify this point.

**Comment by caot** [comment]
You are right. "set (Boost_USE_STATIC_LIBS ON)" did the trick in the file of src/cmake/boost.cmake.

**Pull request closed without merging**
